name: build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.12

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    # https://github.com/golangci/golangci-lint-action
    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
        version: v1.54

        # Optional: working directory, useful for monorepos
        # working-directory: somedir

        # Optional: golangci-lint command line arguments.
        # args: --issues-exit-code=0
        args: --config=.golangci.yml

        # Optional: show only new issues if it's a pull request. The default value is `false`.
        only-new-issues: false

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Test
      run: go test -v ./...

    - name: Update coverage report
      uses: ncruces/go-coverage-report@main

    - name: Build
      run: go build -v ./cmd/gorcon

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: gorcon
        path: |
          *gorcon*